---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, on-prem' 
summary: 온프레미스 ONTAP 클러스터의 새로운 기능에 대해 알아보십시오. 
---
= 온프레미스 ONTAP 클러스터의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
온프레미스 ONTAP 클러스터의 새로운 기능에 대해 알아보십시오.



== 2022년 6월 7일

다음 변경은 커넥터의 3.9.19 릴리스에 도입되었습니다.



=== 새 고급 보기

ONTAP 사내 클러스터의 고급 관리가 필요한 경우에는 ONTAP 시스템과 함께 제공되는 관리 인터페이스인 ONTAP System Manager를 사용하여 이러한 작업을 수행할 수 있습니다. Cloud Manager 인터페이스에 Cloud Manager 인터페이스가 포함되어 있으므로 고급 관리를 위해 Cloud Manager에서 그대로 둘 필요가 없습니다.

이 고급 보기는 9.10.0 이상을 실행하는 온프레미스 ONTAP 클러스터에서 미리 보기로 사용할 수 있습니다. NetApp은 이 경험을 개선하고 다음 릴리즈에서 향상된 기능을 추가할 계획입니다. 제품 내 채팅을 사용하여 피드백을 보내주십시오.

link:task-administer-advanced-view.html["고급 보기에 대해 자세히 알아보십시오"].



== 2022년 2월 27일



=== 디지털 지갑에서 "온-프레미스 ONTAP" 탭을 사용할 수 있습니다.

이제 하드웨어 및 서비스 계약 만료일과 함께 온프레미스 ONTAP 클러스터의 인벤토리를 볼 수 있습니다. 클러스터에 대한 추가 정보도 제공됩니다.

https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/task-discovering-ontap.html#viewing-cluster-information-and-contract-details["이 중요한 온프레미스 클러스터 정보를 확인하는 방법을 알아보십시오"]. 클러스터에 대한 NetApp NSS(Support Site Account)가 있어야 하며 NSS 자격 증명을 Cloud Manager 계정에 연결해야 합니다.



== 2022년 1월 11일



=== 온프레미스 ONTAP 클러스터의 볼륨에 추가하는 태그는 태그 지정 서비스와 함께 사용할 수 있습니다.

볼륨에 추가하는 태그는 이제 애플리케이션 템플릿 서비스의 태그 지정 기능과 연결되어 리소스 관리를 구성하고 단순화할 수 있습니다.



== 2021년 11월 28일



=== 온프레미스 ONTAP 클러스터를 위한 볼륨 생성 마법사가 간소화되었습니다

볼륨 생성 마법사를 재설계했으므로 이제 사용자 지정 엑스포트 정책을 선택할 수 있습니다.



== 2021년 3월 8일



=== Active IQ 서비스에서 사내 ONTAP 클러스터 정보를 사용할 수 있습니다

* Active IQ에서 온프레미스 클러스터 목록(NSS 계정 기반)을 표시하면 버튼을 클릭하여 에 연결할 수 있습니다 link:task-discovering-ontap.html#discovering-clusters-from-the-discovery-page["클러스터를 검색합니다"^] Cloud Manager Canvas에 추가합니다. 따라서 Cloud Manager에서 모든 스토리지 시스템을 쉽게 관리할 수 있습니다.
* Active IQ에서 하나 이상의 클러스터에 펌웨어 업데이트가 필요하다고 결정하면 버튼을 클릭하여 에 추가할 수 있습니다 link:task-managing-ontap.html#downloading-new-disk-and-shelf-firmware["Ansible 플레이북을 다운로드하고 클러스터 펌웨어를 업그레이드합니다"^].
* 새로운 소식 link:task-managing-ontap.html#viewing-on-prem-workloads-that-are-candidates-for-the-cloud["Cloud-Ready 워크로드 탭"^] NetApp이 온프레미스 ONTAP 클러스터에서 클라우드로 이동하는 데 적합한 워크로드 또는 볼륨 목록을 제공합니다. 이러한 볼륨 중 일부를 이동하면 비용을 절감하고 성능과 복원력을 향상시킬 수 있습니다.
+
을 참조하십시오 link:https://www.netapp.com/knowledge-center/what-is-lift-and-shift["리프트 앤 시프트(Lift and Shift)란 무엇입니까?"]


